### ISSUE TITLE
Размер страницы больше, чем размер рабочей области

### ISSUE THREAD

**Issue by shrmnn** [Catlerc/EmojiReanimator#5]
В данный момент размер странички больше, чем это необходимо. При чем сама дополнительная площадь не пользуется даже анимированным фоном.

OS: WIn 10
Resolution: FHD

![catlerc github io_EmojiReanimator_](https://user-images.githubusercontent.com/17484449/126769767-3ac7b2d3-0129-48b4-ab03-cce1994b4731.png)

**Comment by Catlerc** [comment]
Поменял размер, теперь должно быть норм
