### ISSUE TITLE
Независимая от имени генерация эмодзи

### ISSUE THREAD

**Issue by shrmnn** [Catlerc/EmojiReanimator#6]
Сейчас у приложения есть такая проблема, что если новая загруженная референс-картинка имеет такое же название (включая расширение), что и предыдущая, то система считает, что это одна и та же картинка, из-за чего новые эмодзи не генерируются, включая анимации.

![image](https://user-images.githubusercontent.com/17484449/126770698-4a19216f-f6dd-45a4-91de-f887c4842419.png)

**Comment by Catlerc** [comment]
Добавил сброс  input элемента для референса, теперь всё обновляется даже с одинаковыми названиями
